kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dev-team-tiller-binding
  namespace: dev-team
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: dev-team
roleRef:
  kind: Role
  name: dev-team
  apiGroup: rbac.authorization.k8s.io
