kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: dev-team
  name: dev-team
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
